use_frameworks!

platform :ios, '11.0'

target 'SXKit_Example' do
  pod 'SXBaseKit', :path => '../'
#  pod 'SXKit/SXPlayer', :path => '../'
  pod 'SXBaseKit/SXPhotoLibrary', :path => '../'
  pod 'SXBaseKit/SXVideoTrimmerView', :path => '../'
  pod 'SDWebImage'
  target 'SXKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
