#use_frameworks!

platform :ios, '11.0'

target 'SXKit_Example' do
  pod 'SXKit', :path => '../'
  pod 'SXKit/SXPlayer', :path => '../'

  target 'SXKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
